language: python
before_install:
  - pip install coverage
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
python:
  - "3.4"
  - "3.5"
# command to run tests
script:
  - coverage run -m unittest discover -s test/ -p "*_test.py"
